choice_bella_tank_loc = '[alt="Bella Tank"]'
text_one_page_loc = 'text="Bella Tank"'
size_loc = '#option-label-size-143-item-167'
color_loc = '#option-label-color-93-item-50'
button_add_to_cart_loc = '[title="Add to Cart"]'
text_two_page_loc = '.base'
size_text_loc = 'text="S"'
color_text_loc = 'text="Blue"'
data_bind_loc = '[data-bind*="prepareMessageForHtml"]'
counter_number_loc = '.counter-number'
button_add_to_compare_loc = 'xpath=(//a[@title="Add to Compare"])[4]'
text_two_loc = '#compare-items > li > strong > a'
button_add_wish_list_loc = '(//a[@data-action="add-to-wishlist"])[4]'
login_wait_loc = '[name="login[username]"]'
text_page_login_loc = 'text="Customer Login"'
add_email_loc = '[name="login[username]"]'
add_password_loc = '[name="login[password]"]'
button_sign_in_loc = '[name="send"]'
text_pege_my_wish_list_loc = 'text="My Wish List"'
text_add_wish_list_loc = '[data-bind*="prepareMessageForHtml"]'
